####################
# function:     cdrmove()
# purpose:      Perform a CDR move given a certain pointer.
# parameters:   game:a gamestate such as c(-2,-1,4,-5,3)
#               pointer: a particular pointer of the form c(n,-m) generated by the cdrpointers script
# Author:       Joshua Watson & Alyssa Seidman 2015
# Example:      cdrmove(gen.cdrpile(3)[5],cdrpointers(gen.cdrpile(3)[5])[1])
# Dependancies: gen.cdrpile and cdrpointers are recommended (though not needed)

cdrmove <- function(gamestate,pointer){
    
    ##### This block of code finds the index of the block to have CDR performed on it ####
    
    which(unlist(pointer)[1] == gamestate)[[1]]->p1
    which(unlist(pointer)[2] == gamestate)[[1]]->p2
    
    if(abs(p1-p2)==1){ #ie the two numbers are adjacent
        if(p1<p2){ #ie p1 is left of p2
            if(abs(gamestate[p1]>abs(gamestate[p2]))){
                block<-p1
            } else {
                block<-p2
            }
        } else {   #ie p1 is right of p2
            if(abs(gamestate[p1]>abs(gamestate[p2]))){
                block<-p2
            } else {
                block<-p1 
            } #end else            
        } #end else
        
    } else {
        if(p1<p2){  #ie, if p1 is left of p2 not adjacent
            block<-c((p1+1):p2)
        } else {    #ie p1 is right of p2 not adjacent
            block<-c((p2:p1-1))
        } #end else
    } #end else
    
    #### Performs the flip and negation and overwrites block index elements with new neg.block ####
    neg.block<-rev(gamestate[block])*-1
    new.gamestate<-gamestate
    new.gamestate[block]<-neg.block
    new.gamestate
}

####################
# function:     cdrpointers()
# purpose:        Finds the pointers of a particular CDR gamestate and outputs a list of pointer vectors
#               Note that the code works so that the second number is always the negative number.
# parameters:	game: a cdr gamestate in vector form, ie, c(1,2,3,4,5)
#               Example: cdrpointers(c(-2,1,3,-4,5))
# Author:       Joshua Watson & Alyssa Seidman 2015
# Dependancies: none

cdrpointers <- function(gamestate){
    poscount<-0
    pointerlist<-list()
    
    for(i in 1:length(gamestate)){  #Check for all positive or all negative
        if(gamestate[i]>0){
            poscount<-(poscount+1)
        }
    }
    if((poscount==length(gamestate)) || (poscount==0)){
        print("No pointers.")
        break
    }
    
    for(i in 1:length(gamestate)){
        pointer<-gamestate[i]
        if(pointer>0){
            for(j in 1:length(gamestate)){
                pointercheck<-gamestate[j]
                if((pointercheck==-(pointer+1)) | (pointercheck==-(pointer-1))){
                    pointerlist[[length(pointerlist)+1]] <- c(gamestate[i],gamestate[j])
                }
            }
        }
    }
    pointerlist
}