####################
# function:     cdrmove()
# purpose:      Perform a CDR move given a certain pointer.
# parameters:   game:a gamestate such as c(-2,-1,4,-5,3)
#               pointer: a particular pointer of the form c(n,-m) generated by the cdrpointers script
# Author:       Joshua Watson & Alyssa Seidman 2015
# Example:      cdrmove(gen.cdrpile(3)[5],cdrpointers(gen.cdrpile(3)[5])[1])
# Dependancies: none

cdrmove <- function(gamestate,pointer){
    
    ##### This block of code finds the index of the block to have CDR performed on it ####
    
    which(unlist(pointer)[1] == gamestate)[[1]]->p1
    which(unlist(pointer)[2] == gamestate)[[1]]->p2
    
    if(abs(p1-p2)==1){ #ie the two numbers are adjacent
        if(p1<p2){ #ie p1 is left of p2
            if(abs(gamestate[p1]>abs(gamestate[p2]))){
                block<-p1
            } else {
                block<-p2
            }
        } else {   #ie p1 is right of p2
            if(abs(gamestate[p1]>abs(gamestate[p2]))){
                block<-p2
            } else {
                block<-p1 
            } #end else            
        } #end else
        
    } else {
        if(p1<p2){  #ie, if p1 is left of p2 not adjacent
            block<-c((p1+1):p2)
        } else {    #ie p1 is right of p2 not adjacent
            block<-c((p2:p1-1))
        } #end else
    } #end else
    
    #### Performs the flip and negation and overwrites block index elements with new neg.block ####
    neg.block<-rev(gamestate[block])*-1
    new.gamestate<-gamestate
    new.gamestate[block]<-neg.block
    new.gamestate
}